begin;
insert into public.areas(id,city_slug,source_slug,source_area_id,parent_area_id,area_type,slug,name,population,active) values
('es-madrid-neighbourhood:011','madrid','madrid-police-dispatch-incidents','neighbourhood:011','es-madrid-district:01','municipal_neighbourhood','palacio','Palacio',null,true),
('es-madrid-neighbourhood:012','madrid','madrid-police-dispatch-incidents','neighbourhood:012','es-madrid-district:01','municipal_neighbourhood','embajadores','Embajadores',null,true),
('es-madrid-neighbourhood:013','madrid','madrid-police-dispatch-incidents','neighbourhood:013','es-madrid-district:01','municipal_neighbourhood','cortes','Cortes',null,true),
('es-madrid-neighbourhood:014','madrid','madrid-police-dispatch-incidents','neighbourhood:014','es-madrid-district:01','municipal_neighbourhood','justicia','Justicia',null,true),
('es-madrid-neighbourhood:015','madrid','madrid-police-dispatch-incidents','neighbourhood:015','es-madrid-district:01','municipal_neighbourhood','universidad','Universidad',null,true),
('es-madrid-neighbourhood:016','madrid','madrid-police-dispatch-incidents','neighbourhood:016','es-madrid-district:01','municipal_neighbourhood','sol','Sol',null,true),
('es-madrid-neighbourhood:021','madrid','madrid-police-dispatch-incidents','neighbourhood:021','es-madrid-district:02','municipal_neighbourhood','imperial','Imperial',null,true),
('es-madrid-neighbourhood:022','madrid','madrid-police-dispatch-incidents','neighbourhood:022','es-madrid-district:02','municipal_neighbourhood','acacias','Acacias',null,true),
('es-madrid-neighbourhood:023','madrid','madrid-police-dispatch-incidents','neighbourhood:023','es-madrid-district:02','municipal_neighbourhood','chopera','Chopera',null,true),
('es-madrid-neighbourhood:024','madrid','madrid-police-dispatch-incidents','neighbourhood:024','es-madrid-district:02','municipal_neighbourhood','legazpi','Legazpi',null,true),
('es-madrid-neighbourhood:025','madrid','madrid-police-dispatch-incidents','neighbourhood:025','es-madrid-district:02','municipal_neighbourhood','delicias','Delicias',null,true),
('es-madrid-neighbourhood:026','madrid','madrid-police-dispatch-incidents','neighbourhood:026','es-madrid-district:02','municipal_neighbourhood','palos-de-la-frontera','Palos de la Frontera',null,true),
('es-madrid-neighbourhood:027','madrid','madrid-police-dispatch-incidents','neighbourhood:027','es-madrid-district:02','municipal_neighbourhood','atocha','Atocha',null,true),
('es-madrid-neighbourhood:031','madrid','madrid-police-dispatch-incidents','neighbourhood:031','es-madrid-district:03','municipal_neighbourhood','pacifico','Pacífico',null,true),
('es-madrid-neighbourhood:032','madrid','madrid-police-dispatch-incidents','neighbourhood:032','es-madrid-district:03','municipal_neighbourhood','adelfas','Adelfas',null,true),
('es-madrid-neighbourhood:033','madrid','madrid-police-dispatch-incidents','neighbourhood:033','es-madrid-district:03','municipal_neighbourhood','estrella','Estrella',null,true),
('es-madrid-neighbourhood:034','madrid','madrid-police-dispatch-incidents','neighbourhood:034','es-madrid-district:03','municipal_neighbourhood','ibiza','Ibiza',null,true),
('es-madrid-neighbourhood:035','madrid','madrid-police-dispatch-incidents','neighbourhood:035','es-madrid-district:03','municipal_neighbourhood','los-jeronimos','Los Jerónimos',null,true),
('es-madrid-neighbourhood:036','madrid','madrid-police-dispatch-incidents','neighbourhood:036','es-madrid-district:03','municipal_neighbourhood','nino-jesus','Niño Jesús',null,true),
('es-madrid-neighbourhood:041','madrid','madrid-police-dispatch-incidents','neighbourhood:041','es-madrid-district:04','municipal_neighbourhood','recoletos','Recoletos',null,true),
('es-madrid-neighbourhood:042','madrid','madrid-police-dispatch-incidents','neighbourhood:042','es-madrid-district:04','municipal_neighbourhood','goya','Goya',null,true),
('es-madrid-neighbourhood:043','madrid','madrid-police-dispatch-incidents','neighbourhood:043','es-madrid-district:04','municipal_neighbourhood','fuente-del-berro','Fuente del Berro',null,true),
('es-madrid-neighbourhood:044','madrid','madrid-police-dispatch-incidents','neighbourhood:044','es-madrid-district:04','municipal_neighbourhood','guindalera','Guindalera',null,true),
('es-madrid-neighbourhood:045','madrid','madrid-police-dispatch-incidents','neighbourhood:045','es-madrid-district:04','municipal_neighbourhood','lista','Lista',null,true),
('es-madrid-neighbourhood:046','madrid','madrid-police-dispatch-incidents','neighbourhood:046','es-madrid-district:04','municipal_neighbourhood','castellana','Castellana',null,true),
('es-madrid-neighbourhood:051','madrid','madrid-police-dispatch-incidents','neighbourhood:051','es-madrid-district:05','municipal_neighbourhood','el-viso','El Viso',null,true),
('es-madrid-neighbourhood:052','madrid','madrid-police-dispatch-incidents','neighbourhood:052','es-madrid-district:05','municipal_neighbourhood','prosperidad','Prosperidad',null,true),
('es-madrid-neighbourhood:053','madrid','madrid-police-dispatch-incidents','neighbourhood:053','es-madrid-district:05','municipal_neighbourhood','ciudad-jardin','Ciudad Jardín',null,true),
('es-madrid-neighbourhood:054','madrid','madrid-police-dispatch-incidents','neighbourhood:054','es-madrid-district:05','municipal_neighbourhood','hispanoamerica','Hispanoamérica',null,true),
('es-madrid-neighbourhood:055','madrid','madrid-police-dispatch-incidents','neighbourhood:055','es-madrid-district:05','municipal_neighbourhood','nueva-espana','Nueva España',null,true),
('es-madrid-neighbourhood:056','madrid','madrid-police-dispatch-incidents','neighbourhood:056','es-madrid-district:05','municipal_neighbourhood','castilla','Castilla',null,true),
('es-madrid-neighbourhood:061','madrid','madrid-police-dispatch-incidents','neighbourhood:061','es-madrid-district:06','municipal_neighbourhood','bellas-vistas','Bellas Vistas',null,true),
('es-madrid-neighbourhood:062','madrid','madrid-police-dispatch-incidents','neighbourhood:062','es-madrid-district:06','municipal_neighbourhood','cuatro-caminos','Cuatro Caminos',null,true),
('es-madrid-neighbourhood:063','madrid','madrid-police-dispatch-incidents','neighbourhood:063','es-madrid-district:06','municipal_neighbourhood','castillejos','Castillejos',null,true),
('es-madrid-neighbourhood:064','madrid','madrid-police-dispatch-incidents','neighbourhood:064','es-madrid-district:06','municipal_neighbourhood','almenara','Almenara',null,true),
('es-madrid-neighbourhood:065','madrid','madrid-police-dispatch-incidents','neighbourhood:065','es-madrid-district:06','municipal_neighbourhood','valdeacederas','Valdeacederas',null,true),
('es-madrid-neighbourhood:066','madrid','madrid-police-dispatch-incidents','neighbourhood:066','es-madrid-district:06','municipal_neighbourhood','berruguete','Berruguete',null,true),
('es-madrid-neighbourhood:071','madrid','madrid-police-dispatch-incidents','neighbourhood:071','es-madrid-district:07','municipal_neighbourhood','gaztambide','Gaztambide',null,true),
('es-madrid-neighbourhood:072','madrid','madrid-police-dispatch-incidents','neighbourhood:072','es-madrid-district:07','municipal_neighbourhood','arapiles','Arapiles',null,true),
('es-madrid-neighbourhood:073','madrid','madrid-police-dispatch-incidents','neighbourhood:073','es-madrid-district:07','municipal_neighbourhood','trafalgar','Trafalgar',null,true),
('es-madrid-neighbourhood:074','madrid','madrid-police-dispatch-incidents','neighbourhood:074','es-madrid-district:07','municipal_neighbourhood','almagro','Almagro',null,true),
('es-madrid-neighbourhood:075','madrid','madrid-police-dispatch-incidents','neighbourhood:075','es-madrid-district:07','municipal_neighbourhood','rios-rosas','Ríos Rosas',null,true),
('es-madrid-neighbourhood:076','madrid','madrid-police-dispatch-incidents','neighbourhood:076','es-madrid-district:07','municipal_neighbourhood','vallehermoso','Vallehermoso',null,true),
('es-madrid-neighbourhood:081','madrid','madrid-police-dispatch-incidents','neighbourhood:081','es-madrid-district:08','municipal_neighbourhood','el-pardo','El Pardo',null,true),
('es-madrid-neighbourhood:082','madrid','madrid-police-dispatch-incidents','neighbourhood:082','es-madrid-district:08','municipal_neighbourhood','fuentelarreina','Fuentelarreina',null,true),
('es-madrid-neighbourhood:083','madrid','madrid-police-dispatch-incidents','neighbourhood:083','es-madrid-district:08','municipal_neighbourhood','penagrande','Peñagrande',null,true),
('es-madrid-neighbourhood:084','madrid','madrid-police-dispatch-incidents','neighbourhood:084','es-madrid-district:08','municipal_neighbourhood','pilar','Pilar',null,true),
('es-madrid-neighbourhood:085','madrid','madrid-police-dispatch-incidents','neighbourhood:085','es-madrid-district:08','municipal_neighbourhood','la-paz','La Paz',null,true),
('es-madrid-neighbourhood:086','madrid','madrid-police-dispatch-incidents','neighbourhood:086','es-madrid-district:08','municipal_neighbourhood','valverde','Valverde',null,true),
('es-madrid-neighbourhood:087','madrid','madrid-police-dispatch-incidents','neighbourhood:087','es-madrid-district:08','municipal_neighbourhood','mirasierra','Mirasierra',null,true),
('es-madrid-neighbourhood:088','madrid','madrid-police-dispatch-incidents','neighbourhood:088','es-madrid-district:08','municipal_neighbourhood','el-goloso','El Goloso',null,true),
('es-madrid-neighbourhood:091','madrid','madrid-police-dispatch-incidents','neighbourhood:091','es-madrid-district:09','municipal_neighbourhood','casa-de-campo','Casa de Campo',null,true),
('es-madrid-neighbourhood:092','madrid','madrid-police-dispatch-incidents','neighbourhood:092','es-madrid-district:09','municipal_neighbourhood','arguelles','Argüelles',null,true),
('es-madrid-neighbourhood:093','madrid','madrid-police-dispatch-incidents','neighbourhood:093','es-madrid-district:09','municipal_neighbourhood','ciudad-universitaria','Ciudad Universitaria',null,true),
('es-madrid-neighbourhood:094','madrid','madrid-police-dispatch-incidents','neighbourhood:094','es-madrid-district:09','municipal_neighbourhood','valdezarza','Valdezarza',null,true),
('es-madrid-neighbourhood:095','madrid','madrid-police-dispatch-incidents','neighbourhood:095','es-madrid-district:09','municipal_neighbourhood','valdemarin','Valdemarín',null,true),
('es-madrid-neighbourhood:096','madrid','madrid-police-dispatch-incidents','neighbourhood:096','es-madrid-district:09','municipal_neighbourhood','el-plantio','El Plantío',null,true),
('es-madrid-neighbourhood:097','madrid','madrid-police-dispatch-incidents','neighbourhood:097','es-madrid-district:09','municipal_neighbourhood','aravaca','Aravaca',null,true),
('es-madrid-neighbourhood:101','madrid','madrid-police-dispatch-incidents','neighbourhood:101','es-madrid-district:10','municipal_neighbourhood','los-carmenes','Los Cármenes',null,true),
('es-madrid-neighbourhood:102','madrid','madrid-police-dispatch-incidents','neighbourhood:102','es-madrid-district:10','municipal_neighbourhood','puerta-del-angel','Puerta del Ángel',null,true),
('es-madrid-neighbourhood:103','madrid','madrid-police-dispatch-incidents','neighbourhood:103','es-madrid-district:10','municipal_neighbourhood','lucero','Lucero',null,true),
('es-madrid-neighbourhood:104','madrid','madrid-police-dispatch-incidents','neighbourhood:104','es-madrid-district:10','municipal_neighbourhood','aluche','Aluche',null,true),
('es-madrid-neighbourhood:105','madrid','madrid-police-dispatch-incidents','neighbourhood:105','es-madrid-district:10','municipal_neighbourhood','campamento','Campamento',null,true),
('es-madrid-neighbourhood:106','madrid','madrid-police-dispatch-incidents','neighbourhood:106','es-madrid-district:10','municipal_neighbourhood','cuatro-vientos','Cuatro Vientos',null,true),
('es-madrid-neighbourhood:107','madrid','madrid-police-dispatch-incidents','neighbourhood:107','es-madrid-district:10','municipal_neighbourhood','aguilas','Águilas',null,true),
('es-madrid-neighbourhood:111','madrid','madrid-police-dispatch-incidents','neighbourhood:111','es-madrid-district:11','municipal_neighbourhood','comillas','Comillas',null,true),
('es-madrid-neighbourhood:112','madrid','madrid-police-dispatch-incidents','neighbourhood:112','es-madrid-district:11','municipal_neighbourhood','opanel','Opañel',null,true),
('es-madrid-neighbourhood:113','madrid','madrid-police-dispatch-incidents','neighbourhood:113','es-madrid-district:11','municipal_neighbourhood','san-isidro','San Isidro',null,true),
('es-madrid-neighbourhood:114','madrid','madrid-police-dispatch-incidents','neighbourhood:114','es-madrid-district:11','municipal_neighbourhood','vista-alegre','Vista Alegre',null,true),
('es-madrid-neighbourhood:115','madrid','madrid-police-dispatch-incidents','neighbourhood:115','es-madrid-district:11','municipal_neighbourhood','puerta-bonita','Puerta Bonita',null,true),
('es-madrid-neighbourhood:116','madrid','madrid-police-dispatch-incidents','neighbourhood:116','es-madrid-district:11','municipal_neighbourhood','buenavista','Buenavista',null,true),
('es-madrid-neighbourhood:117','madrid','madrid-police-dispatch-incidents','neighbourhood:117','es-madrid-district:11','municipal_neighbourhood','abrantes','Abrantes',null,true),
('es-madrid-neighbourhood:121','madrid','madrid-police-dispatch-incidents','neighbourhood:121','es-madrid-district:12','municipal_neighbourhood','orcasitas','Orcasitas',null,true),
('es-madrid-neighbourhood:122','madrid','madrid-police-dispatch-incidents','neighbourhood:122','es-madrid-district:12','municipal_neighbourhood','orcasur','Orcasur',null,true),
('es-madrid-neighbourhood:123','madrid','madrid-police-dispatch-incidents','neighbourhood:123','es-madrid-district:12','municipal_neighbourhood','san-fermin','San Fermín',null,true),
('es-madrid-neighbourhood:124','madrid','madrid-police-dispatch-incidents','neighbourhood:124','es-madrid-district:12','municipal_neighbourhood','almendrales','Almendrales',null,true),
('es-madrid-neighbourhood:125','madrid','madrid-police-dispatch-incidents','neighbourhood:125','es-madrid-district:12','municipal_neighbourhood','moscardo','Moscardó',null,true),
('es-madrid-neighbourhood:126','madrid','madrid-police-dispatch-incidents','neighbourhood:126','es-madrid-district:12','municipal_neighbourhood','zofio','Zofío',null,true),
('es-madrid-neighbourhood:127','madrid','madrid-police-dispatch-incidents','neighbourhood:127','es-madrid-district:12','municipal_neighbourhood','pradolongo','Pradolongo',null,true),
('es-madrid-neighbourhood:131','madrid','madrid-police-dispatch-incidents','neighbourhood:131','es-madrid-district:13','municipal_neighbourhood','entrevias','Entrevías',null,true),
('es-madrid-neighbourhood:132','madrid','madrid-police-dispatch-incidents','neighbourhood:132','es-madrid-district:13','municipal_neighbourhood','san-diego','San Diego',null,true),
('es-madrid-neighbourhood:133','madrid','madrid-police-dispatch-incidents','neighbourhood:133','es-madrid-district:13','municipal_neighbourhood','palomeras-bajas','Palomeras Bajas',null,true),
('es-madrid-neighbourhood:134','madrid','madrid-police-dispatch-incidents','neighbourhood:134','es-madrid-district:13','municipal_neighbourhood','palomeras-sureste','Palomeras Sureste',null,true),
('es-madrid-neighbourhood:135','madrid','madrid-police-dispatch-incidents','neighbourhood:135','es-madrid-district:13','municipal_neighbourhood','portazgo','Portazgo',null,true),
('es-madrid-neighbourhood:136','madrid','madrid-police-dispatch-incidents','neighbourhood:136','es-madrid-district:13','municipal_neighbourhood','numancia','Numancia',null,true),
('es-madrid-neighbourhood:141','madrid','madrid-police-dispatch-incidents','neighbourhood:141','es-madrid-district:14','municipal_neighbourhood','pavones','Pavones',null,true),
('es-madrid-neighbourhood:142','madrid','madrid-police-dispatch-incidents','neighbourhood:142','es-madrid-district:14','municipal_neighbourhood','horcajo','Horcajo',null,true),
('es-madrid-neighbourhood:143','madrid','madrid-police-dispatch-incidents','neighbourhood:143','es-madrid-district:14','municipal_neighbourhood','marroquina','Marroquina',null,true),
('es-madrid-neighbourhood:144','madrid','madrid-police-dispatch-incidents','neighbourhood:144','es-madrid-district:14','municipal_neighbourhood','media-legua','Media Legua',null,true),
('es-madrid-neighbourhood:145','madrid','madrid-police-dispatch-incidents','neighbourhood:145','es-madrid-district:14','municipal_neighbourhood','fontarron','Fontarrón',null,true),
('es-madrid-neighbourhood:146','madrid','madrid-police-dispatch-incidents','neighbourhood:146','es-madrid-district:14','municipal_neighbourhood','vinateros','Vinateros',null,true),
('es-madrid-neighbourhood:151','madrid','madrid-police-dispatch-incidents','neighbourhood:151','es-madrid-district:15','municipal_neighbourhood','ventas','Ventas',null,true),
('es-madrid-neighbourhood:152','madrid','madrid-police-dispatch-incidents','neighbourhood:152','es-madrid-district:15','municipal_neighbourhood','pueblo-nuevo','Pueblo Nuevo',null,true),
('es-madrid-neighbourhood:153','madrid','madrid-police-dispatch-incidents','neighbourhood:153','es-madrid-district:15','municipal_neighbourhood','quintana','Quintana',null,true),
('es-madrid-neighbourhood:154','madrid','madrid-police-dispatch-incidents','neighbourhood:154','es-madrid-district:15','municipal_neighbourhood','la-concepcion','La Concepción',null,true),
('es-madrid-neighbourhood:155','madrid','madrid-police-dispatch-incidents','neighbourhood:155','es-madrid-district:15','municipal_neighbourhood','san-pascual','San Pascual',null,true),
('es-madrid-neighbourhood:156','madrid','madrid-police-dispatch-incidents','neighbourhood:156','es-madrid-district:15','municipal_neighbourhood','san-juan-bautista','San Juan Bautista',null,true),
('es-madrid-neighbourhood:157','madrid','madrid-police-dispatch-incidents','neighbourhood:157','es-madrid-district:15','municipal_neighbourhood','colina','Colina',null,true),
('es-madrid-neighbourhood:158','madrid','madrid-police-dispatch-incidents','neighbourhood:158','es-madrid-district:15','municipal_neighbourhood','atalaya','Atalaya',null,true),
('es-madrid-neighbourhood:159','madrid','madrid-police-dispatch-incidents','neighbourhood:159','es-madrid-district:15','municipal_neighbourhood','costillares','Costillares',null,true),
('es-madrid-neighbourhood:161','madrid','madrid-police-dispatch-incidents','neighbourhood:161','es-madrid-district:16','municipal_neighbourhood','palomas','Palomas',null,true),
('es-madrid-neighbourhood:162','madrid','madrid-police-dispatch-incidents','neighbourhood:162','es-madrid-district:16','municipal_neighbourhood','piovera','Piovera',null,true),
('es-madrid-neighbourhood:163','madrid','madrid-police-dispatch-incidents','neighbourhood:163','es-madrid-district:16','municipal_neighbourhood','canillas','Canillas',null,true),
('es-madrid-neighbourhood:164','madrid','madrid-police-dispatch-incidents','neighbourhood:164','es-madrid-district:16','municipal_neighbourhood','pinar-del-rey','Pinar del Rey',null,true),
('es-madrid-neighbourhood:165','madrid','madrid-police-dispatch-incidents','neighbourhood:165','es-madrid-district:16','municipal_neighbourhood','apostol-santiago','Apóstol Santiago',null,true),
('es-madrid-neighbourhood:166','madrid','madrid-police-dispatch-incidents','neighbourhood:166','es-madrid-district:16','municipal_neighbourhood','valdefuentes','Valdefuentes',null,true),
('es-madrid-neighbourhood:171','madrid','madrid-police-dispatch-incidents','neighbourhood:171','es-madrid-district:17','municipal_neighbourhood','villaverde-alto-casco-historico-de-villaverde','Villaverde Alto - Casco Histórico de Villaverde',null,true),
('es-madrid-neighbourhood:172','madrid','madrid-police-dispatch-incidents','neighbourhood:172','es-madrid-district:17','municipal_neighbourhood','san-cristobal','San Cristóbal',null,true),
('es-madrid-neighbourhood:173','madrid','madrid-police-dispatch-incidents','neighbourhood:173','es-madrid-district:17','municipal_neighbourhood','butarque','Butarque',null,true),
('es-madrid-neighbourhood:174','madrid','madrid-police-dispatch-incidents','neighbourhood:174','es-madrid-district:17','municipal_neighbourhood','los-rosales','Los Rosales',null,true),
('es-madrid-neighbourhood:175','madrid','madrid-police-dispatch-incidents','neighbourhood:175','es-madrid-district:17','municipal_neighbourhood','angeles','Ángeles',null,true),
('es-madrid-neighbourhood:181','madrid','madrid-police-dispatch-incidents','neighbourhood:181','es-madrid-district:18','municipal_neighbourhood','casco-historico-de-vallecas','Casco Histórico de Vallecas',null,true),
('es-madrid-neighbourhood:182','madrid','madrid-police-dispatch-incidents','neighbourhood:182','es-madrid-district:18','municipal_neighbourhood','santa-eugenia','Santa Eugenia',null,true),
('es-madrid-neighbourhood:183','madrid','madrid-police-dispatch-incidents','neighbourhood:183','es-madrid-district:18','municipal_neighbourhood','ensanche-de-vallecas','Ensanche de Vallecas',null,true),
('es-madrid-neighbourhood:191','madrid','madrid-police-dispatch-incidents','neighbourhood:191','es-madrid-district:19','municipal_neighbourhood','casco-historico-de-vicalvaro','Casco Histórico de Vicálvaro',null,true),
('es-madrid-neighbourhood:192','madrid','madrid-police-dispatch-incidents','neighbourhood:192','es-madrid-district:19','municipal_neighbourhood','valdebernardo','Valdebernardo',null,true),
('es-madrid-neighbourhood:193','madrid','madrid-police-dispatch-incidents','neighbourhood:193','es-madrid-district:19','municipal_neighbourhood','valderrivas','Valderrivas',null,true),
('es-madrid-neighbourhood:194','madrid','madrid-police-dispatch-incidents','neighbourhood:194','es-madrid-district:19','municipal_neighbourhood','el-canaveral','El Cañaveral',null,true),
('es-madrid-neighbourhood:201','madrid','madrid-police-dispatch-incidents','neighbourhood:201','es-madrid-district:20','municipal_neighbourhood','simancas','Simancas',null,true),
('es-madrid-neighbourhood:202','madrid','madrid-police-dispatch-incidents','neighbourhood:202','es-madrid-district:20','municipal_neighbourhood','hellin','Hellín',null,true),
('es-madrid-neighbourhood:203','madrid','madrid-police-dispatch-incidents','neighbourhood:203','es-madrid-district:20','municipal_neighbourhood','amposta','Amposta',null,true),
('es-madrid-neighbourhood:204','madrid','madrid-police-dispatch-incidents','neighbourhood:204','es-madrid-district:20','municipal_neighbourhood','arcos','Arcos',null,true),
('es-madrid-neighbourhood:205','madrid','madrid-police-dispatch-incidents','neighbourhood:205','es-madrid-district:20','municipal_neighbourhood','rosas','Rosas',null,true),
('es-madrid-neighbourhood:206','madrid','madrid-police-dispatch-incidents','neighbourhood:206','es-madrid-district:20','municipal_neighbourhood','rejas','Rejas',null,true),
('es-madrid-neighbourhood:207','madrid','madrid-police-dispatch-incidents','neighbourhood:207','es-madrid-district:20','municipal_neighbourhood','canillejas','Canillejas',null,true),
('es-madrid-neighbourhood:208','madrid','madrid-police-dispatch-incidents','neighbourhood:208','es-madrid-district:20','municipal_neighbourhood','el-salvador','El Salvador',null,true),
('es-madrid-neighbourhood:211','madrid','madrid-police-dispatch-incidents','neighbourhood:211','es-madrid-district:21','municipal_neighbourhood','alameda-de-osuna','Alameda de Osuna',null,true),
('es-madrid-neighbourhood:212','madrid','madrid-police-dispatch-incidents','neighbourhood:212','es-madrid-district:21','municipal_neighbourhood','aeropuerto','Aeropuerto',null,true),
('es-madrid-neighbourhood:213','madrid','madrid-police-dispatch-incidents','neighbourhood:213','es-madrid-district:21','municipal_neighbourhood','casco-historico-de-barajas','Casco Histórico de Barajas',null,true),
('es-madrid-neighbourhood:214','madrid','madrid-police-dispatch-incidents','neighbourhood:214','es-madrid-district:21','municipal_neighbourhood','timon','Timón',null,true),
('es-madrid-neighbourhood:215','madrid','madrid-police-dispatch-incidents','neighbourhood:215','es-madrid-district:21','municipal_neighbourhood','corralejos','Corralejos',null,true)
    on conflict(id) do update set
      city_slug=excluded.city_slug,
      source_slug=excluded.source_slug,
      source_area_id=excluded.source_area_id,
      parent_area_id=excluded.parent_area_id,
      area_type=excluded.area_type,
      slug=excluded.slug,
      name=excluded.name,
      population=excluded.population,
      active=excluded.active;
    
commit;
