begin;

        insert into public.observations(
          area_id,source_slug,metric_slug,period_start,period_end,value,unit,numerator,denominator,provenance
        ) values
        ('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-informado-servicio-externo','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-infraccion-a-otras-oomm-y-normas','2026-08-01','2026-08-31',7,'count',7,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-infracciones-al-trafico-y-seguridad-vial','2026-08-01','2026-08-31',21,'count',21,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-infracciones-ley-seguridad-ciudadana','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-llamada-erronea','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-manifestaciones-concentraciones','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-no-se-envia-recurso','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-normas-de-convivencia','2026-08-01','2026-08-31',1,'count',1,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-nota-informativa','2026-08-01','2026-08-31',2,'count',2,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-otras-actuaciones','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-otros-delitos','2026-08-01','2026-08-31',4,'count',4,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-pruebas','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-resolucion-conflictos-privados','2026-08-01','2026-08-31',8,'count',8,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-reyertas-agresiones','2026-08-01','2026-08-31',1,'count',1,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-robos-con-fuerza','2026-08-01','2026-08-31',4,'count',4,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-robos-con-violencia-intimidacion','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-ruidos-molestos','2026-08-01','2026-08-31',5,'count',5,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-seg-vial-colaboracion-en-materia-de-trafico-y-movilidad','2026-08-01','2026-08-31',1,'count',1,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-seguridad-colabracion-con-otros-cuerpos-o-servicios','2026-08-01','2026-08-31',1,'count',1,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-servicio-especial-de-proteccion','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-servicios-especiales-diversos','2026-08-01','2026-08-31',1,'count',1,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-simulacros','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-sucesos-colaboraciones-con-otros-servicios','2026-08-01','2026-08-31',6,'count',6,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-sustraccion-de-vehiculo','2026-08-01','2026-08-31',1,'count',1,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-venta-ambulante','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb),
('es-madrid-neighbourhood:215','madrid-police-dispatch-incidents','madrid-dispatch-violencia-de-genero-y-familiar','2026-08-01','2026-08-31',0,'count',0,null,'{"source_month":"2026-08","resource_id":"837676-16-incidencias-recibidas-en-la-emisora-central-de-policia-municipal","measurement":"municipal_police_central_dispatch_incidents","geography_model":"source_assigned_neighbourhood_current_official_boundary"}'::jsonb)
        on conflict(area_id,source_slug,metric_slug,period_start,period_end,unit) do update set
          value=excluded.value,
          numerator=excluded.numerator,
          denominator=excluded.denominator,
          provenance=excluded.provenance;
        
commit;
