-- dataSec universal model
-- Designed for Supabase/Postgres 17 + PostGIS.
-- Public tables are read-only to anon/authenticated; writes are reserved for service_role.

create extension if not exists postgis with schema extensions;

-- Supabase projects can carry broad default Data API grants.
-- Keep future public objects opt-in and grant only what dataSec needs below.
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke execute on functions from public;

create table if not exists public.countries (
  code text primary key check (char_length(code) = 2),
  name text not null
);

create table if not exists public.cities (
  slug text primary key,
  country_code text not null references public.countries(code),
  name text not null,
  timezone text not null
);

create index if not exists cities_country_code_idx
  on public.cities (country_code);

create table if not exists public.sources (
  slug text primary key,
  authority text not null,
  source_url text not null,
  licence text,
  update_frequency text,
  source_type text not null,
  granularity text,
  notes text
);

create table if not exists public.areas (
  id text primary key,
  city_slug text not null references public.cities(slug),
  source_slug text not null references public.sources(slug),
  source_area_id text not null,
  parent_area_id text references public.areas(id),
  area_type text not null,
  slug text not null,
  name text not null,
  population integer,
  active boolean not null default true,
  unique (city_slug, source_slug, source_area_id)
);

create index if not exists areas_source_slug_idx
  on public.areas (source_slug);

create index if not exists areas_parent_area_id_idx
  on public.areas (parent_area_id)
  where parent_area_id is not null;

create table if not exists public.area_boundaries (
  area_id text not null references public.areas(id) on delete cascade,
  source_slug text not null references public.sources(slug),
  period_start date not null,
  geometry extensions.geometry(MultiPolygon, 4326) not null,
  source_hash text,
  primary key (area_id, period_start)
);

create index if not exists area_boundaries_geometry_gix
  on public.area_boundaries using gist (geometry);

create index if not exists area_boundaries_source_period_idx
  on public.area_boundaries (source_slug, period_start desc);

create table if not exists public.metrics (
  slug text primary key,
  label text not null,
  family text not null,
  description text,
  higher_is_worse boolean
);

create table if not exists public.observations (
  area_id text not null references public.areas(id) on delete cascade,
  source_slug text not null references public.sources(slug),
  metric_slug text not null references public.metrics(slug),
  period_start date not null,
  period_end date not null,
  value numeric not null,
  unit text not null,
  numerator numeric,
  denominator numeric,
  provenance jsonb not null default '{}'::jsonb,
  primary key (area_id, source_slug, metric_slug, period_start, period_end, unit)
);

create index if not exists observations_area_period_idx
  on public.observations (area_id, period_start desc);

create index if not exists observations_metric_period_idx
  on public.observations (metric_slug, period_start desc);

create index if not exists observations_source_period_idx
  on public.observations (source_slug, period_start desc);

create table if not exists public.area_population_snapshots (
  area_id text not null references public.areas(id) on delete cascade,
  source_slug text not null references public.sources(slug),
  period_start date not null,
  population integer not null check (population >= 0),
  provenance jsonb not null default '{}'::jsonb,
  primary key (area_id, source_slug, period_start)
);

create index if not exists area_population_snapshots_area_period_idx
  on public.area_population_snapshots (area_id, period_start desc);

create table if not exists public.ingestion_runs (
  id text primary key,
  source_slug text not null references public.sources(slug),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null check (status in ('running','passed','failed','quarantined')),
  source_version text,
  row_count integer,
  matched_row_count integer,
  checksum text,
  diagnostics jsonb not null default '{}'::jsonb
);

create index if not exists ingestion_runs_source_started_idx
  on public.ingestion_runs (source_slug, started_at desc);

create table if not exists public.data_quality_flags (
  id bigint generated by default as identity primary key,
  ingestion_run_id text not null references public.ingestion_runs(id) on delete cascade,
  severity text not null check (severity in ('info','warning','error')),
  code text not null,
  message text not null,
  details jsonb not null default '{}'::jsonb
);

create index if not exists data_quality_flags_run_idx
  on public.data_quality_flags (ingestion_run_id);

create or replace view public.latest_area_boundaries
with (security_invoker = true)
as
select distinct on (area_id)
  area_id,
  source_slug,
  period_start,
  geometry,
  source_hash
from public.area_boundaries
order by area_id, period_start desc;


create or replace view public.latest_area_boundaries_geojson
with (security_invoker = true)
as
select
  area_id,
  source_slug,
  period_start,
  extensions.ST_AsGeoJSON(geometry)::jsonb as geojson,
  source_hash
from public.latest_area_boundaries;

create or replace view public.latest_area_boundaries_map_geojson
with (security_invoker = true)
as
select
  area_id,
  source_slug,
  period_start,
  extensions.ST_AsGeoJSON(
    extensions.ST_SimplifyPreserveTopology(geometry, 0.00015)
  )::jsonb as geojson
from public.latest_area_boundaries;

create or replace view public.area_month_context
with (security_invoker = true)
as
with totals as (
  select
    a.id as area_id,
    a.city_slug,
    o.period_start,
    sum(o.value)::numeric as total_incidents,
    extensions.ST_Area(b.geometry::extensions.geography) / 1000000.0 as area_km2
  from public.observations o
  join public.areas a on a.id = o.area_id
  join public.area_boundaries b
    on b.area_id = o.area_id
   and b.period_start = o.period_start
  group by
    a.id,
    a.city_slug,
    o.period_start,
    b.geometry
),
density as (
  select
    *,
    case
      when area_km2 > 0 then total_incidents / area_km2
      else null
    end as incidents_per_km2
  from totals
)
select
  area_id,
  city_slug,
  period_start,
  total_incidents,
  area_km2,
  incidents_per_km2,
  percent_rank() over (
    partition by city_slug, period_start
    order by incidents_per_km2 nulls last
  ) as density_percentile
from density;

grant usage on schema public to anon, authenticated, service_role;

-- Remove any project-level implicit grants before defining the public API surface.
revoke all on public.countries, public.cities, public.sources, public.areas,
  public.area_boundaries, public.metrics, public.observations
from anon, authenticated;

-- Public product data: read-only from the browser.
grant select on public.countries, public.cities, public.sources, public.areas,
  public.area_boundaries, public.metrics, public.observations
to anon, authenticated;


create or replace function public.find_area_at_point(
  p_lon double precision,
  p_lat double precision
)
returns table (
  area_id text,
  source_area_id text,
  name text,
  city_slug text
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    a.id as area_id,
    a.source_area_id,
    a.name,
    a.city_slug
  from public.latest_area_boundaries b
  join public.areas a on a.id = b.area_id
  where a.active = true
    and extensions.ST_Covers(
      b.geometry,
      extensions.ST_SetSRID(extensions.ST_Point(p_lon, p_lat), 4326)
    )
  order by
    case when a.area_type like '%neighbourhood%' then 0 else 1 end,
    extensions.ST_Area(b.geometry::extensions.geography) asc
  limit 1;
$$;

revoke all on function public.find_area_at_point(double precision, double precision)
from public, anon, authenticated;

grant execute on function public.find_area_at_point(double precision, double precision)
to anon, authenticated, service_role;


create or replace view public.latest_area_context
with (security_invoker = true)
as
select distinct on (area_id)
  area_id,
  city_slug,
  period_start,
  total_incidents,
  area_km2,
  incidents_per_km2,
  density_percentile
from public.area_month_context
order by area_id, period_start desc;

create or replace view public.latest_area_population
with (security_invoker = true)
as
select distinct on (area_id)
  area_id,
  source_slug,
  period_start,
  population,
  provenance
from public.area_population_snapshots
order by area_id, period_start desc;

create or replace view public.latest_area_map_metrics
with (security_invoker = true)
as
with latest_context as (
  select * from public.latest_area_context
),
category_agg as (
  select
    c.area_id,
    c.city_slug,
    c.period_start,
    c.total_incidents,
    c.area_km2,
    c.incidents_per_km2,
    c.density_percentile,
    sum(o.value) filter (
      where
        (c.city_slug = 'madrid' and o.metric_slug in (
          'madrid-dispatch-amenazas-y-atentados-terroristas',
          'madrid-dispatch-atentado-agresion-a-empleado-publico',
          'madrid-dispatch-fallecidos-por-delito-o-causa-desconocida',
          'madrid-dispatch-hurtos',
          'madrid-dispatch-otros-delitos',
          'madrid-dispatch-reyertas-agresiones',
          'madrid-dispatch-robos-con-fuerza',
          'madrid-dispatch-robos-con-violencia-intimidacion',
          'madrid-dispatch-sustraccion-de-vehiculo',
          'madrid-dispatch-violencia-de-genero-y-familiar'
        ))
        or
        (c.city_slug = 'london' and o.metric_slug not in ('all-crime', 'anti-social-behaviour'))
    )::numeric as crime_related_count,
    sum(o.value) filter (
      where
        (c.city_slug = 'madrid' and o.metric_slug in (
          'madrid-dispatch-atentado-agresion-a-empleado-publico',
          'madrid-dispatch-fallecidos-por-delito-o-causa-desconocida',
          'madrid-dispatch-reyertas-agresiones',
          'madrid-dispatch-robos-con-fuerza',
          'madrid-dispatch-robos-con-violencia-intimidacion',
          'madrid-dispatch-sustraccion-de-vehiculo',
          'madrid-dispatch-violencia-de-genero-y-familiar'
        ))
        or
        (c.city_slug = 'london' and o.metric_slug in (
          'violent-crime','robbery','burglary','criminal-damage-arson',
          'vehicle-crime','possession-of-weapons'
        ))
    )::numeric as violence_property_count,
    sum(o.value) filter (
      where
        (c.city_slug = 'madrid' and o.metric_slug in (
          'madrid-dispatch-hurtos',
          'madrid-dispatch-robos-con-fuerza',
          'madrid-dispatch-robos-con-violencia-intimidacion',
          'madrid-dispatch-sustraccion-de-vehiculo'
        ))
        or
        (c.city_slug = 'london' and o.metric_slug in (
          'theft-from-the-person','other-theft','shoplifting',
          'bicycle-theft','vehicle-crime','robbery'
        ))
    )::numeric as theft_count
  from latest_context c
  join public.observations o
    on o.area_id = c.area_id
   and o.period_start = c.period_start
  group by c.area_id, c.city_slug, c.period_start, c.total_incidents,
           c.area_km2, c.incidents_per_km2, c.density_percentile
),
with_population as (
  select
    a.*,
    p.population,
    case when a.area_km2 > 0 then a.crime_related_count / a.area_km2 end as crime_related_per_km2,
    case when a.area_km2 > 0 then a.violence_property_count / a.area_km2 end as violence_property_per_km2,
    case when a.area_km2 > 0 then a.theft_count / a.area_km2 end as theft_per_km2,
    case when p.population > 0 then a.crime_related_count * 10000.0 / p.population end as crime_related_per_10k,
    case when p.population > 0 then a.violence_property_count * 10000.0 / p.population end as violence_property_per_10k,
    case when p.population > 0 then a.theft_count * 10000.0 / p.population end as theft_per_10k
  from category_agg a
  left join public.area_population_snapshots p
    on p.area_id = a.area_id
   and p.period_start = a.period_start
)
select
  *,
  percent_rank() over (partition by city_slug, period_start order by crime_related_per_km2 nulls last)
    as crime_related_density_percentile,
  percent_rank() over (partition by city_slug, period_start order by violence_property_per_km2 nulls last)
    as violence_property_density_percentile,
  percent_rank() over (partition by city_slug, period_start order by theft_per_km2 nulls last)
    as theft_density_percentile,
  case when population is not null then
    percent_rank() over (partition by city_slug, period_start order by crime_related_per_10k nulls last)
  end as crime_related_resident_percentile,
  case when population is not null then
    percent_rank() over (partition by city_slug, period_start order by violence_property_per_10k nulls last)
  end as violence_property_resident_percentile,
  case when population is not null then
    percent_rank() over (partition by city_slug, period_start order by theft_per_10k nulls last)
  end as theft_resident_percentile
from with_population;

grant select on public.latest_area_boundaries,
  public.latest_area_boundaries_geojson,
  public.latest_area_boundaries_map_geojson,
  public.area_month_context,
  public.latest_area_context,
  public.latest_area_population,
  public.latest_area_map_metrics
to anon, authenticated, service_role;

-- Backend ingestion may write via the service role.
grant select, insert, update, delete on public.countries, public.cities, public.sources,
  public.areas, public.area_boundaries, public.metrics, public.observations,
  public.area_population_snapshots, public.ingestion_runs, public.data_quality_flags
to service_role;

grant usage, select on all sequences in schema public to service_role;

-- Internal pipeline tables remain invisible to browser roles.
revoke all on public.ingestion_runs, public.data_quality_flags from anon, authenticated;

alter table public.countries enable row level security;
alter table public.cities enable row level security;
alter table public.sources enable row level security;
alter table public.areas enable row level security;
alter table public.area_boundaries enable row level security;
alter table public.metrics enable row level security;
alter table public.observations enable row level security;
alter table public.area_population_snapshots enable row level security;
alter table public.ingestion_runs enable row level security;
alter table public.data_quality_flags enable row level security;

drop policy if exists "countries public read" on public.countries;
create policy "countries public read"
on public.countries for select to anon, authenticated using (true);

drop policy if exists "cities public read" on public.cities;
create policy "cities public read"
on public.cities for select to anon, authenticated using (true);

drop policy if exists "sources public read" on public.sources;
create policy "sources public read"
on public.sources for select to anon, authenticated using (true);

drop policy if exists "areas public read" on public.areas;
create policy "areas public read"
on public.areas for select to anon, authenticated using (true);

drop policy if exists "area boundaries public read" on public.area_boundaries;
create policy "area boundaries public read"
on public.area_boundaries for select to anon, authenticated using (true);

drop policy if exists "metrics public read" on public.metrics;
create policy "metrics public read"
on public.metrics for select to anon, authenticated using (true);

drop policy if exists "observations public read" on public.observations;
create policy "observations public read"
on public.observations for select to anon, authenticated using (true);


drop policy if exists "area population public read" on public.area_population_snapshots;
create policy "area population public read"
on public.area_population_snapshots for select to anon, authenticated using (true);

grant select on public.area_population_snapshots to anon, authenticated;
